---
repeat_interval: 1s
pgw_config:
  url: http://127.0.0.1:9091
  timeout: 30s
  namespace: vault_reliability_exporter
  job: vault_reliability_job
  basic_auth:
    username: login
    password: pwd
  labels:
    env: test
vault_config:
  url: https://127.0.0.1:8200
  timeout: 30s
  profiles:
    - name: userpass
      auth_path: auth/userpass/login/guest
      auth_data:
        password: guest
      secret_path: test/userpass-write
      secret_data:
        foo: bar
    - name: token
      auth_token: VAULT_TOKEN
      secret_path: test/token-write
