---
# repeat_interval: 1s
# delay: 0s
# listen_address: :8080
pgw_config:
  url: http://127.0.0.1:9091
  # timeout: 30s
  # namespace: vault_reliability_exporter
  # job: vault_reliability_job
  # basic_auth:
  #   username: login
  #   password: pwd
  # labels:
  #   env: test
vault_config:
  url: https://127.0.0.1:8200
  # timeout: 30s
  # max_retries: 2
  profiles:
    - name: userpass
      # Value may be rewritten by VRE_PROFILE_USERPASS_AUTH_PATH environment variable
      auth_path: auth/userpass/login/guest
      # Value may be rewritten by VRE_PROFILE_USERPASS_AUTH_DATA environment variable
      auth_data:
        password: guest
      secret_path: probe-secrets/test
      # revoke_token: false
      # secret_data:
      #   foo: bar
    - name: token
      # Value may be rewritten by VRE_PROFILE_TOKEN_AUTH_TOKEN environment variable
      auth_token: VAULT_TOKEN
      # secret_path: probe-secrets/test
# telemetry_config:
#   pushgateway_enabled: true
#   http_enabled: false
